### ISSUE TITLE
End dimension crashing on entering the portal

### ISSUE THREAD

**Issue by mudddober** [EvergoodTeam/EvergoodReforged#2]
This is the second time i have tried to play this pack. When i go through the end portal the game crashes. When i try to rejoin world the screen flashes and crashes immediately. Have tried several things and nothing has worked yet. Had to load backup to play.

**Comment by Librv** [comment]
Sorry for the late reply, combination of notifications not working and dedicating time elsewhere.
This doesn't appear to happen anymore in the update that is being worked on (port to 1.18.2).
