### ISSUE TITLE
Opening crystal chest crash

### ISSUE THREAD

**Issue by Vohcksall** [EvergoodTeam/EvergoodReforged#3]
Any time i open a crystal chest the server immediately crashes with an overflow error. Breaking the chest doesnt cause a crash but using a hopper to get the items out does, so does sneaking and looking at a chest. The clients dont crash only the server does

**Comment by Librv** [comment]
Sorry for the late reply, combination of notifications not working and dedicating time elsewhere.
This was a problem on the mod's end and it was fixed with [Iron Chests 13.0.7](https://www.curseforge.com/minecraft/mc-mods/iron-chests/files/3583838). It will be included with the next modpack update.
